[package]
name = "combat-theater"
version = "0.1.0"
authors = ["matszczygiel <mateusz.szczygiel@student.uw.edu.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.14.0"
log = "0.4.8"
simplelog = "0.6.0"